import type { Metadata } from "next";
import type { ReactNode } from "react";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Bookmarks Manager",
  description: "Generated by the Fista Digital FTE.",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header className="border-b">
          <nav aria-label="Main navigation" className="p-4">
            <ul className="flex flex-wrap gap-4">
          <li><Link href="/" className="hover:underline">Bookmark saving page</Link></li>
          <li><Link href="/bookmarks-browsing-page" className="hover:underline">Bookmarks browsing page</Link></li>
            </ul>
          </nav>
        </header>
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}
